/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pocketsdr_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(67ab2f0ba1ff388917cfa61e4f62f981)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pocketsdr/pocketsdr_source.h>
#include <gnuradio/pocketsdr/raw_unpack.h>
// pydoc.h is automatically generated in the build directory
#include <pocketsdr_source_pydoc.h>

void bind_pocketsdr_source(py::module& m)
{

    using pocketsdr_source    = gr::pocketsdr::pocketsdr_source;


    py::class_<pocketsdr_source, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<pocketsdr_source>>(m, "pocketsdr_source", D(pocketsdr_source))

        .def(py::init(&pocketsdr_source::make),
           py::arg("conf_file"),
           py::arg("channels"),
           D(pocketsdr_source,make)
        )
        .def("get_sample_rate", &pocketsdr_source::get_sample_rate)
        .def("get_center_freq", &pocketsdr_source::get_center_freq,
           py::arg("i"))
        .def("overruns", &pocketsdr_source::overruns)
        ;

    // raw stream unpack (also used by the bit-exact regression test)
    m.def("unpack_raw", &gr::pocketsdr::unpack_raw,
          py::arg("raw"), py::arg("nsamp"), py::arg("ns"), py::arg("ch"),
          py::arg("IQ"), py::arg("bits"));
}
